In [1]:
import tensorflow as tf


# Tensor Initialization and Casting

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2, 0., -3, 8.1, 90], dtype = tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.int16)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.   0.  -3.   8.1 90. ], shape=(5,), dtype=float32)
tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)


In [ ]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string = tf.constant(["hello world", "hi"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


In [ ]:
tensor_one_d = tf.constant([2, 0., -3, 8.1, 90], dtype = tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.   0.  -3.   8.1 90. ], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [ ]:
tensor_two_d = tf.constant([
                          [1, 2, 0],
                           [3, 5, -1],
                           [2, 4, 5]])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 2  4  5]], shape=(3, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
                            [[1, 2, 0], [3, 5, -1]],
                            [[10, 2, 0], [1, 0, 2]],
                            [[5, 8, 0], [2, 3, 4]],
                            [[5, 8, 0], [2, 3, 4]]
                              ])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  3  4]]

 [[ 5  8  0]
  [ 2  3  4]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
tensor_four_d = tf.constant([[
                            [[1, 2, 0], [3, 5, -1]],
                            [[10, 2, 0], [1, 0, 2]],
                            [[5, 8, 0], [2, 3, 4]],
                            [[5, 8, 0], [2, 3, 4]]
                            ],
                             [
                            [[1, 2, 0], [3, 5, -1]],
                            [[10, 2, 0], [1, 0, 2]],
                            [[5, 10, 0], [2, 3, 4]],
                            [[5, 8, 0], [2, 30, 4]]
                              ]])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  3  4]]

  [[ 5  8  0]
   [ 2  3  4]]]


 [[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5 10  0]
   [ 2  3  4]]

  [[ 5  8  0]
   [ 2 30  4]]]], shape=(2, 4, 2, 3), dtype=int32)


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1, 2, 4])
print(np_array)

[1 2 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
             num_rows = 3,
             num_columns =None,
             batch_shape = None,
             dtype = tf.dtypes.float32,
             name = None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
fill_tensor = tf.fill([1, 3, 4], 5, name = None)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [ ]:
ones_tensor = tf.ones(
                      [5, 3, 2],
                      dtype = tf.dtypes.float32,
                      name = None
                     )
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [ ]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [ ]:
zeros_tensor = tf.zeros(
                        [3, 2],
                        dtype = tf.dtypes.float32,
                        name = None
                        )
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [ ]:
print(tensor_three_d.ndim)

3


In [ ]:
print(tensor_three_d.shape)

(4, 2, 3)


In [ ]:
print(tf.shape(tensor_three_d))

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


In [ ]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
print(tf.size(t))
tf.rank(t)

tf.Tensor(12, shape=(), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
print(tf.size(t))

tf.Tensor(12, shape=(), dtype=int32)


In [ ]:
random_tensor = tf.random.normal([3, 2], mean = 0.0, stddev = 1.0, dtype = tf.dtypes.float32, seed = None, name = None)
print(random_tensor)

tf.Tensor(
[[ 1.1785142  -0.54290986]
 [-0.42179978  0.48427892]
 [-1.1997995  -0.5346898 ]], shape=(3, 2), dtype=float32)


In [ ]:
random_uniform_tensor = tf.random.uniform(
                     [5,],
                     minval = 0,
                     maxval = None,
                     dtype = tf.dtypes.float32,
                     seed = None,
                     name = None
)
print(random_uniform_tensor)

tf.Tensor([0.96633923 0.3966123  0.58203876 0.75125647 0.564322  ], shape=(5,), dtype=float32)


In [ ]:
tf.random.set_seed(3)
print(tf.random.uniform(shape = [3,], maxval = 5, dtype = tf.int32, seed = 10))
print(tf.random.uniform(shape = [3,], maxval = 5, dtype = tf.int32, seed = 10))
print(tf.random.uniform(shape = [3,], maxval = 5, dtype = tf.int32, seed = 10))
print(tf.random.uniform(shape = [3,], maxval = 5, dtype = tf.int32, seed = 10))

tf.Tensor([3 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 3 1], shape=(3,), dtype=int32)
tf.Tensor([2 1 3], shape=(3,), dtype=int32)
tf.Tensor([2 1 2], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(3)
print(tf.random.uniform(shape = [3,], maxval = 5, dtype = tf.int32, seed = 10))
print(tf.random.uniform(shape = [3,], maxval = 5, dtype = tf.int32, seed = 1))


tf.Tensor([3 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 0 3], shape=(3,), dtype=int32)


# Tensor Indexing

In [ ]:
tensor_indexed = tf.constant([3, 6, 2, 4, 6, 66, 7])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:6])
print(tensor_indexed[1:6:2])
print(tensor_indexed[:4])
print(tensor_indexed[3:])
print(tensor_indexed[3:-1])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 4  6 66  7], shape=(4,), dtype=int32)
tf.Tensor([ 4  6 66], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[1, 2, 0],
                           [3, 5, -1],
                           [1, 5, 6],
                           [2, 3, 8]])
print(tensor_two_d[0:3, :2 ])
print(tensor_two_d[2, : ])
print(tensor_two_d[1:3, 0])
print(tensor_two_d[..., 1])
print(tensor_two_d[:, 1])

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)
tf.Tensor([1 5 6], shape=(3,), dtype=int32)
tf.Tensor([3 1], shape=(2,), dtype=int32)
tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)
tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
                            [[1, 2, 0], [3, 5, -1]],
                            [[10, 2, 0], [1, 0, 2]],
                            [[5, 8, 0], [2, 3, 4]],
                            [[5, 8, 0], [2, 3, 4]]
                              ])
print(tensor_three_d[0 ,:, :])
print(tensor_three_d[0 ,:, 0:-1])
print(tensor_three_d[... ,:, 0])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [3 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 1  3]
 [10  1]
 [ 5  2]
 [ 5  2]], shape=(4, 2), dtype=int32)


# Math operations


In [8]:
x_abs = tf.constant([-2.25, 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [9]:
tf.abs(tf.constant(-0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.2>

In [11]:
x_abs_complex = tf.constant([-2.25 + 4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [14]:
tf.sqrt(3.33)

<tf.Tensor: shape=(), dtype=float32, numpy=1.8248287>

In [13]:
x_1 = tf.constant([5, 3, 6, 6, 4, 6], dtype = tf.int32)
x_2 = tf.constant([7, 6, 2, 6, 7, 11], dtype = tf.int32)
print(tf.multiply(x_1, x_2))
print(tf.divide(x_1, x_2))

tf.Tensor([35 18 12 36 28 66], shape=(6,), dtype=int32)
tf.Tensor([0.71428571 0.5        3.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)


In [15]:
print(tf.math.divide_no_nan(x_1, x_2))

tf.Tensor([0.71428571 0.5        3.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)


In [18]:
x_1 = tf.constant([5, 3, 6, 6, 4, 6], dtype = tf.float32)
x_2 = tf.constant([7], dtype = tf.float32)
x_2_stretched = tf.constant([7, 7, 7, 7, 7, 7], dtype = tf.float32)

print(tf.math.add(x_1, x_2))
print(tf.math.add(x_1, x_2_stretched))

tf.Tensor([12. 10. 13. 13. 11. 13.], shape=(6,), dtype=float32)
tf.Tensor([12. 10. 13. 13. 11. 13.], shape=(6,), dtype=float32)


In [21]:
x_1 = tf.constant([[5, 3, 6, 6, 4, 6]], dtype = tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype = tf.float32)
print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1, x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [27]:
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                       [3, 11, 16, 1, 8],
                       [14, 45, 23, 5, 27]])
print(x_argmax.shape)
print(tf.math.argmax(x_argmax, 0))

(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)


In [28]:
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                       [3, 11, 16, 1, 8],
                       [14, 45, 23, 5, 27]])
print(x_argmax.shape)
print(tf.math.argmax(x_argmax, axis = 1))

(3, 5)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [25]:
x_argmax = tf.constant([200, 120, 130, 3, 6])
print(tf.math.argmax(x_argmax))

tf.Tensor(0, shape=(), dtype=int64)


In [26]:
x_argmin = tf.constant([200, 120, 130, 3, 6])
print(tf.math.argmin(x_argmin))

tf.Tensor(3, shape=(), dtype=int64)


In [30]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[3, 0], [1, 4]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]], dtype=int32)>

In [31]:
tf.pow(tf.constant(2), tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [32]:
tensor_two_d = tf.constant([[1, 2, 0],
                            [3, 5, -1],
                            [1, 5, 6],
                            [2, 3, 8]])
print(tf.math.reduce_sum(tensor_two_d, axis = None, keepdims = False, name = None))

tf.Tensor(35, shape=(), dtype=int32)


In [33]:
tensor_two_d = tf.constant([[1, 2, 0],
                            [3, 5, -1],
                            [1, 5, 6],
                            [2, 3, 8]])
print(tf.math.reduce_max(tensor_two_d, axis = None, keepdims = False, name = None))

tf.Tensor(8, shape=(), dtype=int32)


In [34]:
tensor_two_d = tf.constant([[1, 2, 0],
                            [3, 5, -1],
                            [1, 5, 6],
                            [2, 3, 8]])
print(tf.math.reduce_sum(tensor_two_d, axis = 0, keepdims = False, name = None))

tf.Tensor([ 7 15 13], shape=(3,), dtype=int32)


In [36]:
tensor_two_d = tf.constant([[1, 2, 0],
                            [3, 5, -1],
                            [1, 5, 6],
                            [2, 3, 8]], dtype = tf.float16)
print(tf.math.reduce_std(tensor_two_d, axis = 0, keepdims = False, name = None))

tf.Tensor([0.829 1.299 3.832], shape=(3,), dtype=float16)


In [37]:
tf.math.top_k(tensor_two_d)

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=float16, numpy=
array([[2.],
       [5.],
       [6.],
       [8.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [1],
       [2],
       [2]], dtype=int32)>)

In [38]:
tf.math.top_k(tensor_two_d,  k = 2)

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[2., 1.],
       [5., 3.],
       [6., 5.],
       [8., 3.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 0],
       [1, 0],
       [2, 1],
       [2, 1]], dtype=int32)>)

# Linear algebra

In [41]:
x_1 = tf.constant([[1, 2, 0],
                   [3, 5, -1]])
x_2 = tf.constant([[1, 2, 0],
                   [3, 5, -1],
                   [4, 5, 6]])
print(x_1.shape, x_2.shape)
tf.linalg.matmul(x_1, x_2, transpose_a = False, transpose_b = False, adjoint_b = False,
                 a_is_sparse = False, b_is_sparse = False, output_type = None, name = None)

(2, 3) (3, 3)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  7,  12,  -2],
       [ 14,  26, -11]], dtype=int32)>

In [42]:
print(x_1@x_2)

tf.Tensor(
[[  7  12  -2]
 [ 14  26 -11]], shape=(2, 3), dtype=int32)


In [44]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  3],
       [ 2,  5],
       [ 0, -1]], dtype=int32)>

In [45]:
x_1.T = 3, 2

In [47]:
print(x_1.T)

(3, 2)


In [49]:
x_1 = tf.constant([[[1, 2], [3, 5]],
                   [[10, 2], [1, 0]],
                   [[5, 8], [2, 3]],
                   [[5, 8], [2, 3]]
                              ])
x_2 = tf.constant([[[1, 2, 0], [3, 5, -1]],
                   [[10, 2, 0], [1, 0, 2]],
                   [[5, 8, 0], [2, 3, 4]],
                   [[5, 8, 0], [2, 3, 4]]
                              ])
print(tf.linalg.matmul(x_1, x_2))


tf.Tensor(
[[[  7  12  -2]
  [ 18  31  -5]]

 [[102  20   4]
  [ 10   2   0]]

 [[ 41  64  32]
  [ 16  25  12]]

 [[ 41  64  32]
  [ 16  25  12]]], shape=(4, 2, 3), dtype=int32)


In [54]:
x_1 = tf.constant([[0, 0],
                  [0, 2]])
x_2 = tf.constant([[1, 0, 0],
                  [0, 0, 0]])
tf.linalg.matmul(x_1, x_2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [55]:
tensor_two_d = tf.constant([[1, -2, 0],
                           [3, 5, 100],
                           [1, 5, 6],
                           [2, 3, 8]])
tf.linalg.band_part(tensor_two_d, 0, 0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 6],
       [0, 0, 0]], dtype=int32)>

In [ ]:
# useful special cases:
tf.linalg.band_part(input, 0,-1) # upper triangular part
tf.linalg.band_part(input, -1, 0) # lower traingular part
tf.linalg.band_part(input, 0, 0) # diagonal

In [56]:
tensor_two_d = tf.constant([[1, -2, 0],
                           [3, 5, 100],
                           [1, 5, 6],])
tf.linalg.band_part(tensor_two_d, 0, 0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 6]], dtype=int32)>

In [3]:
tensor_two_d = tf.constant([[1, -2, 0],
                           [3, 5, 100],
                           [1, 5, 6]], dtype = tf.float32)
tensor_two_d_inv = tf.linalg.inv(tensor_two_d)

In [6]:
s, u, v = tf.linalg.svd(tensor_two_d)

In [7]:
print(s)
print(u)

tf.Tensor([100.3663      5.1059036   1.2371687], shape=(3,), dtype=float32)
tf.Tensor(
[[-7.4980810e-04 -3.7569830e-01  9.2674178e-01]
 [ 9.9803799e-01 -5.8300879e-02 -2.2827482e-02]
 [ 6.2606096e-02  9.2490643e-01  3.7500489e-01]], shape=(3, 3), dtype=float32)


In [ ]:
A = np.array([[2, 6, 5, 2],
             [2, -2, 3, 2],
             [1, 5, 4, 0]])
B = np.array([[2, 9, 0, 3, 0],
             [3, 6, 8, -2, 2],
             [1, 3, 5, 0, 1]])

# Ragged Tensor

In [9]:
tensor_two_d = tf.constant([[1, 2, 0],
                            [3, 5, -1],
                            [1, 5, 6],
                            [2, 3, 8]])
print(tensor_two_d.shape)

(4, 3)


In [13]:
tensor_two_d = ([[1, 2, 0],
                            [3,],
                            [1, 5, 6, 5, 6],
                            [2, 3]])
tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged.shape)
print(tensor_ragged)

(4, None)
<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>


In [14]:
print(tf.RaggedTensor.from_row_lengths(
    values = [3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths = [4, 0, 3, 1, 0]
))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


# Sparse Tensor

In [15]:
tensor_sparse = tf.sparse.SparseTensor(
    indices = [[1, 1], [3, 4]], values = [11, 56], dense_shape = [5, 6]
)

In [16]:
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [17]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

# String tensors

In [18]:
tensor_string = tf.constant(["hello", "i am", "a string"])
print(tensor_string)

tf.Tensor([b'hello' b'i am' b'a string'], shape=(3,), dtype=string)


In [22]:
tf.strings.join(tensor_string, separator = " ")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello i am a string'>

# Tensor variables

In [23]:
x = tf.constant([1, 2])

In [26]:
x_var = tf.Variable(x, name = 'var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [33]:
x_var.assign_sub([3, 4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([-2, -2], dtype=int32)>

In [35]:
with tf.device('GPU:0'):
 x_var = tf.Variable(0.2)
print(x_var)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.2>
